name: Create VM on GCP

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  create-instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Google Auth
      uses: 'google-github-actions/auth@v0'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Create VM
      run: |
        gcloud compute instances create githubvm \
          --image-family  debian-10 \
          --image-project debian-cloud \
          --machine-type e2-medium \
          --zone europe-west3-a

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Build and Run Docker Container
      run: |
        docker run --name nginx -d -p 80:80 kofolak80/github:master
